---
title: "Combining Messages & Demo Features"
author: "Coco Yu, Madison Herrmann and JJC"
date: "`r lubridate::today()`"
format: 
  html: 
    embed-resources: true
    toc: true 
    toc_depth: 4
editor_options: 
  chunk_output_type: console
params:
  version: "v1"
---

## Status and Notes

This file combines liwc & demographic features


## Set up

```{r}
#| include: false

options(conflicts.policy = "depends.ok")
library(tidyverse) 

source("https://github.com/jjcurtin/lab_support/blob/main/format_path.R?raw=true")
source("https://github.com/jjcurtin/lab_support/blob/main/fun_eda.R?raw=true")

path_shared <- format_path("risk/data_processed/shared")
path_features <- format_path("risk/data_processed/messages")
```

Read in feature files
```{r}
messages <- read_csv(here::here(path_shared, "features_liwc_day_24h.csv"), 
                show_col_types = FALSE) 
demos <- read_csv(here::here(path_shared, "features_demographics.csv"), 
                  show_col_types = FALSE) 
strat <- read_csv(here::here(path_shared, "strat_lh.csv"), 
                    show_col_types = FALSE) 
```

Check rows

- OK
```{r}
nrow(messages)
nrow(demos)
nrow(strat)
```

Verify expected # of subids

- Full sample (154) for demos
- Messages sample (150) for liwc

```{r}
messages |> distinct(subid) |> nrow() 
demos |> distinct(subid) |> nrow() 
strat |> distinct(subid) |> nrow() 
```

Look at features for each signal

- liwc looks good 

```{r}
names(messages)[1:700]
names(messages)[701:1399]
names(demos)
names(strat)
```

Join messages and demographics
Also join in strat lh
```{r}
nrow(messages)
all <- messages |> 
  left_join(demos, by = c("subid")) |>
  left_join(strat, by = c("subid"))

nrow(all)
```

Check outcome.  Looks good!
```{r}
all |> tab(lapse) 
```

Write out file
```{r}
all |> write_csv(here::here(path_features, 
                            str_c("features_", 
                                  params$version, ".csv")))
```