---
format: 
  pdf: 
    include-in-header: 
    # edit these paths depending on your QMD's location relative to lab_support
      - ../../../../lab_support/templates/latex/define_headers_arc.tex 
      - ../../../../lab_support/templates/latex/includes.tex
geometry: margin=.5in
mainfont: TimesNewRomanPSMT #ArialMT
sansfont: TimesNewRomanPSMT #ArialMT
fontsize: 12pt
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/national-library-of-medicine-grant-proposals.csl # NIH grants
# csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl # APA format
bibliography: paper_messages.bib
---

```{=html}
<!--
1.  DTx address treatment access problems and are somewhat effective.  
2.  Smart dtx (sensing and algorithms) can improve effectiveness by anticipating lapses and personalizing interventions
3.  There has been some progress building algorithms  using EMA but these are limited by burden, sustainatiblity, temporal precision, and by the limits of our  understanding of lapse causes
4.  Text message sensing may address all of these limitations
5.  We now have methods to engineer features from text.  They may differ in predictive performance and interpretabilty.  

so our aims are....
-->
```

# Specific Aims

## Background

According to National Survey on Drug Use and Health (NSDUH), 29.5 million people age 12 and older had alcohol use disorder (AUD) in the past year. However, only 2.2 million (less than 10%) in this age group received alcohol treatment [@nationalinstituteonalcoholabuseandalcoholismAlcoholTreatmentUnited2023; @nationalinstituteonalcoholabuseandalcoholismAlcoholUseDisorder2023]. Provider availability in rural areas, fear of stigma, and economic hardship all contribute to racial, gender and age disparities in treatment seeking [@abrahamAvailabilityMedicationsTreatment2020; @dibartoloAlcoholUseDisorder2017; @youngDifferencesPerceptionsPractices2018; @kaufmannTreatmentSeekingBarriers2014; @schulerPerceivedBarriersTreatment2015; @verissimoInfluenceGenderRace2017]. The emergence of digital therapeutics (DTx) has provided new opportunities to address such health disparity in underprivileged groups with its higher accessibility, acceptability and at least modest efficacy [@beukenhorstUsingSmartphonesReduce2022a; @jacobsonUsingDigitalTherapeutics2023; @mckayEfficacyComparativeEffectiveness2022a; @perskiAcceptabilityDigitalHealth2021]. The broad goal of this program of research is to improve the effectiveness of DTx, by adding personal sensing capabilities and algorithms that allow DTx to have more refined capacities in anticipating lapses and personalizing interventions and supports to meet individuals' momentary needs [@baeMobilePhoneSensors2018a; @leeDataDrivenDigitalTherapeutics2023; @carreiroMHealthDetectionIntervention2018a]

Machine learning models leveraging ecological momentary assessment (EMA) measures have performed relatively well to predict goal-inconsistent alcohol use (e.g., lapses), yet this methodology is associated with several limitations. As it actively relies on self-reports, it places some measurement burden on users. This is particularly problematic as AUD is a chronic disease that requires constant risk monitoring. Reducing sampling rates and number of survey items might reduce this burden but at the cost of impairing prediction precision and temporal specificity. Further, selection of EMA items is based on a top-down, theory-driven approach that may be limited by historical biases in the research literature (e.g., over-representation of white, males).  Given this,  we might miss important constructs that predict lapses among individuals from groups that have been less well-studied. 

<!-- This next paragraph is still very choppy with respect to ideas -->
Passive sensing using text message monitoring provides an opportunity to address the above issues while still retaining some benefits of EMA. As text sensing is both passive and continuous, it simultaneously lowers measurement burden while maintaining a high sampling frequency. Research has found that users report more willingness to use passive sensing measures (vs. active) for as long as one year [@wyantAcceptabilityPersonalSensing2023a]. Some feature engineering techniques allow researchers to mine underlying constructs of texts. They are unconstrained and are thus less susceptible to knowledge gaps. They are also less biased towards previous research samples (i.e., White males). In the meantime, passive sensing methods can still attain some benefits of EMA measures. EMA measures encompass robust predictors that are supported by decades of research. Some feature engineering methods in text analysis can still seize benefits of this theory-driven approach by feeding algorithms with well-established risk factors. For example, sentiment analysis can reveal emotional tones, resembling subjective feelings measures in EMA.

<!-- I  dont know what you mean by "high predictability."  How is that related to who and why? -->
<!-- also, this paragraph seems to be trying to say that you can use these methods because they have interpretable features but also that some methods dont have intepretable features.  This seems like two different ideas that require different paragraphs.  Both are important -->
Machine learning algorithms that use features from text messaging as inputs can be informative of both *who* may lapse and *why* that lapse may occur. Language analysis can identify heavy drinkers and risky drinking behaviors. Indeed, natural language processing (NLP) techniques on electronic health records and clinical notes have demonstrated moderate performance in predicting alcohol misuse, risky alcohol use and alcohol use status [@afsharNaturalLanguageProcessing2019; @vydiswaranAutomateddetectionRiskyAlcohol2024; @toValidationAlcoholMisuse2020; @topazExtractingAlcoholSubstance2019; @alzoubiAutomatedSystemIdentifying2018]. Some NLP methods can also potentially derive interpretable features that might optimize DTx design to customize recommended treatment at the moment. For example, LIWC (see *Section Customized Dictionary*) might deepen our understanding of psycholinguistic risk factors [@tausczikPsychologicalMeaningWords2010a]. Sentimental analysis weighing emotional tone might have implications for emotion-focused therapy. Some NLP techniques generate features empirically and make them less interpretable. Topic modeling examines hidden semantic patterns and identifies clusters of topics from text. Depending on the derived clusters, they might reveal cautionary topics that trigger alcohol use. Other NLP methods such as word embeddings might be less interpretable. 

## Current Study

In the current study, we will use several classic and/or emerging NLP feature engineering techniques applied to participants text messages over a period of three months. We will use features from these techniques as inputs to models that predict alcohol lapses. We will evaluate both model performance and interpretability of each distinct method. Followings are the more specific aims:

**Aim 1: Train and evaluate performance of machine learning models using language features derived from different NLP techniques to predict alcohol lapses.** We will use various feature engineering methods such as topic modeling, sentiment analysis, bag of words, word embeddings and customized dictionary. For each distinct feature set derived from these natural language processing techniques, we will train machine learning models using several contemporary statistical algoritms (e.g.. glmnet, k-nearest neighbor (KNN), linear/quadratic discriminant analysis (LDA/QDA), random forest (RF), XGBoost).  We will evaluate and statistically compare the model performance, quantified as area under the receiver operating characteristic curve (auROC), across models that differ by feature engineering technique. 

**Aim 2: Identify important features and evaluate their interpretability with respect to recommending interventions.** Model interpretation is key to providing treatment recommendations and uncovering potential causes of lapses. We will use contemporary approaches to quantify feature importance (e.g., SHAP) of features within each of the NLP techniques used. 

**Aim 3: Examine model fairness in historically underprivileged subgroup populations.** It is also important to note that if embedded algorithms perform relatively worse for marginalized groups, their use can exacerbate rather than alleviate treatment disparities. As such, model performance between privileged vs. unprivileged groups should be carefully examined. We will evaluate model performance in demographic subgroups that face excessive barriers accessing alcohol treatments or medications, including females, racial minorities, individuals living under poverty, and older population. 
\newpage

# Significance

AUD remains a prevalent, lasting and costly problem in the United States over the past few years. According to 2022 NSDUH [@nationalinstituteonalcoholabuseandalcoholismAlcoholTreatmentUnited2023; @nationalinstituteonalcoholabuseandalcoholismAlcoholUseDisorder2023], an estimate of 29.5 million (10.5% of the population) individuals aged 12 or older had AUD in 2022, which is consistent with the estimates for 2021. AUD problems have also brought huge economic burdens to the U.S., where excessive alcohol use has cost \$223.5 billion in 2006 and \$249 billion in 2010 [@sacks2010NationalState2015a]. 

Despite the high prevalence of AUD, limited number of individuals receive alcohol treatments. Only a small portion (7.6%) of individuals aged 12 or older with AUD acquired alcohol use treatment in the past year [@nationalinstituteonalcoholabuseandalcoholismAlcoholTreatmentUnited2023; @nationalinstituteonalcoholabuseandalcoholismAlcoholUseDisorder2023]. This low treatment acquisition rate is even more pronounced for individuals from disadvantaged groups. Disparities in treatment-seeking behavior based on race, gender, and age are evident [@abrahamAvailabilityMedicationsTreatment2020; @dibartoloAlcoholUseDisorder2017; @youngDifferencesPerceptionsPractices2018; @kaufmannTreatmentSeekingBarriers2014; @schulerPerceivedBarriersTreatment2015; @verissimoInfluenceGenderRace2017]. Only 6.6% of Black or African-American people, 3.8% of people of two or more races, and 4.8% of Hispanic or Latino people with past-year AUD received treatments [@nationalinstituteonalcoholabuseandalcoholismAlcoholTreatmentUnited2023; @nationalinstituteonalcoholabuseandalcoholismAlcoholUseDisorder2023]. Women are less likely to obtain treatments compared to men, even if they have equivalent level of perceived need for help [@gilbertGenderDifferencesUse2019b].

Several obstacles hinder people's utilization of treatment options. Previous studies have identified that AUD patients face financial barriers [@kaufmannTreatmentSeekingBarriers2014; @schulerPerceivedBarriersTreatment2015], lack of knowledge or awareness [@williamsBarriersFacilitatorsAlcohol2018; @probstAlcoholUseDisorder2015; @mayBarriersTreatmentAlcohol2019], social stigma [@sedarousCultureStigmaInequities2023; @finnPerceivedBarriersSeeking2023; @wallhedfinnAlcoholConsumptionDependence2014; @mayBarriersTreatmentAlcohol2019], and geographical barriers [@gregoryFirstlineMedicationsOutpatient2022] for accessing care. Individuals with disadvantaged demographic background suffer from even heightened barriers to treatment resources. Women with high severity of alcohol use face larger fear of stigma compared to their male counterparts [@finnPerceivedBarriersSeeking2023]. 

DTx is an emerging tool that may partially address extant challenges AUD patients face for treatment and continuing care. DTx are evidence-based health software that deliver assessments, interventions, and other supports to patients to prevent, treat, or manage a disease or disorder. Available evidence suggests they are generally effective for mental health conditions including AUD and demonstrate clear clinical advantages [@philippeDigitalHealthInterventions2022; @lecomteMobileAppsMental2020; @gustafsonSmartphoneApplicationSupport2014b]. Further, DTx may provide better access for hard-to-reach populations, including those from socially marginalized group who encounter increased barriers to access treatment. They can benefit patients from rural areas with low provider availability as they are accessible remotely via mobile phones [@bucciTheyAreNot2019; @jacobsonUsingDigitalTherapeutics2023]. DTx also have potentials to relieve barriers to seek professional help resulting from stigma concerns as they can facilitate anonymity and shorten the need for in-person interactions. They are of lower costs compared to in person care and have the capacity to be scalable.

The concept of "smart" DTx is emerging in recent years allowing us to expand the benefits of DTx. Smart DTx comprises two key components. First, they rely on personal sensing methods to collect data. Ideally, sensing should be 1) feasible and place low burden on users; 2) longitudinal; and 3) with high temporal granularity. Exemplary <!-- is it exemplary?  I thought you said it was burdensome? -->measures include EMA, which actively prompts users to complete surveys and can encompass desired questions on moods, social relationships, stressful events, etc. More passive sensing approaches include the measurement of geolocation, phone call logs and text messages collection. GPS tracking, phone logs sharing and SMS message sharing continuously and passively gather information. Combined with self-reports, smart DTx are capable of acquiring contextual information such as levels of support user can obtain from their frequently visited places and frequently contacted people.<!-- is this important if  you don;t plan to use context for your study? -->

Second, the rich dataset extracted from personal sensing can be incorporated into machine learning algorithms. The goal of such models is to identify *who* are at heightened risk for alcohol lapses, *when* they will lapse, and *why* they are at increased risk. Through the embedded algorithms, smart DTx can achieve two tasks: 1) continuous AUD relapse risk-monitoring; and 2) individualized, just-in-time treatment recommendations when needed. Notably, these functions are very important given the dynamic nature of alcohol relapse. AUD is a chronic, dynamic and temporally varying disease where patients face constant challenges of relapsing after abstinence [@scottPathwaysRelapseTreatment2005; @anderssonRelapseInpatientSubstance2019;@witkiewitzModelingComplexityPosttreatment2007a].

To develop such algorithms, we must first identify a clinically relevant outcome to predict.
This outcome should be clearly and precisely defined across individuals, easy to measure, and with high temporal precision. Relapse, which usually refers to the return of a symptomatic behavior, is hard to quantify due to its multidimensional nature and temporal coarseness [@millerWhatRelapseFifty1996]. One potential conceptualization of alcohol relapse is linked to problems of use. Nonetheless, negative consequences are multifaceted and can therefore be burdensome to collect. It is also unclear what the onset of problems are. Another possible outcome is quantity of alcohol use. However, this measure is not temporally precise because there will be a time lag between onset of drinking and the last drink completed. Levels of drinking might also mean differently for individuals with different AUD severity, which makes it hardly generalizable across individuals. Alternatively, in this study, we utilize lapse (i.e., a single episode of alcohol use) as our primary outcome variable. Lapses are easy to define, have a clear onset, and are also clinically meaningful. They can serve as an early warning sign of failure to sustain a desired behavioral change [@chungRelapseAlcoholOther2006a; @marlattRelapsePreventionMaintenance2005a]. Research has also shown that initial lapse and frequent lapses are the associated with enhanced risk of relapse [@witkiewitzRelapsePreventionAlcohol2004b; @hogstrombrandtPredictionSingleEpisodes1999a].

Next we need to determine what inputs to use for our prediction model. The features should be easy to measure and feasible. The widespread availability of smartphones has rendered constant data collection with DTx attainable. Data collection procedure should not be unduly burdensome to users to ensure that sensing is sustainable. Previous research has established satisfying acceptability of active self-report measures such as EMA and even more willingness to use passive sensing measures [@wyantAcceptabilityPersonalSensing2023a]. The features should also be well-validated. For example, GPS tracking has high accuracy in locating individuals and is temporally precise. Text sensing captures precisely the interactions between users and other individuals via SMS.

<!-- dont focus on classifying.  We work with probabilities directly, not class labels -->
<!-- I also dont get how the latter part of this paragraph relates to you topic sentence -->
Desirable features should meaningfully predict lapse risks. More specifically, they should be capable of detecting increased lapse risks in a timely manner. These predictions allow windows for subsequent just-in-time intervention to prevent lapses targeting a specific person. Notably, in the current work, we will emphasize on estimating probabilities of lapsing instead of precise anticipation of lapse occurrence. Under this approach, we can avoid finding a threshold to yield class labels (lapse vs. no lapses).

We can derive top-performing features both from a theory-driven approach and a empirically-driven approach. A theory-driven approach involves integrating domain-specific knowledge of known risks for alcohol lapses from a relapse prevention model into the algorithms. Such features are pre-specified <!-- wouldnt bottom up features be multifacetd as well?  Couldnt they also involve these constructs?  This doesnt seem to be the key distinctions between top down and bottom-up -->and might involve affect state, social interactions, and alcohol-related factors. For instance, the majority of an inpatient teen sample reported initial relapse to alcohol when offered alcohol, when in negative state, and when in interpersonal conflicts [@brownCharacteristicsRelapseFollowing1989]. Other commonly found risk factors include alcohol craving [@mckayStudiesFactorsRelapse1999a; @korlakuntaReasonsRelapsePatients2012], negative affect state [@mckayStudiesFactorsRelapse1999a], cognitive factors [@mckayStudiesFactorsRelapse1999a], and interpersonal problem [@mckayStudiesFactorsRelapse1999a]. Contrarily, a empirically-driven approach starts with collecting data from various sources and then extracts relevant features. The features generated from this method are completely dependent on data. Notably, it is possible to yield features align with known risk factors but not guaranteed. <!-- I dont know what yo mean by at a granular level?   Doesnt bottom up instead cast a wide net and then establishes which features to use based on empirical relationships with the outcome rather than theory? -->

<!-- You start by talking about tempral granularity but then the pargraph is about proximal predictors.  I dont get the connection from what you write here.  You need to unpack more-->
Features should also have temporal granularity given the dynamic nature of alcohol relapse risks. Smart DTx algorithms with good temporal precision should consistently collect data on situated, risk-relevant predictors while retaining low burden on users. Exemplary features with good temporal precision might involve the proximal factors depicted in the relapse prevention model  [@witkiewitzModelingComplexityPosttreatment2007a; @mckayConceptualMethodologicalAnalytical2006b; @feingoldProximalVsDistal2015]. Proximal factors (e.g., drinking partner, drinking behavior) are situated and can be fluctuating over time. They usually occurs before an episode of alcohol use [@chihPredictiveModelingAddiction2014a]. They can be elusive to therapists' attention due to infrequent visits, highlighting importance of sustained monitoring to prevent lapses. 

<!-- Useful algorithms predict well.  They dont find features.  Also, I am confused by why you are back to bottom up vs. top down.  You addressed that two paragraphs ago and moved on? -->
Useful risk prediction algorithms are capable of identifying unrecognized risk factors for lapses. The bottom-up approach does not pre-specify indexes when building models. This method is therefore less susceptible to our knowledge gaps and might even discover previously unfound underlying processes contributing to alcohol lapses. We might even expect less differential performance under the bottom up approach across privileged vs. unprivileged groups because the features are not drawn from past research dominated by White males with AUD and are thus potentially unbiased towards privileged groups.

Smart DTx algorithms should also incorporate features that are interpretable and can map on to current interventions. Exemplary features that are highly interpretable include those derived from the top-down, theory-driven approach. These features are easy to interpret and closely align with established therapies. For example, features related to social relationship might have important implications for family or marital counseling. Affect state features might be informative of emotion-focused therapy. In addition to selecting interpretable features during data training, computational methods can also be used to enhance model interpretability by analyzing feature importance. For instance, we can examine global feature importance to determine which features contribute the most to predict lapses across individuals. Further, examining local feature importance (i.e., features influencing a single observation) in these models might also be helpful for model interpretation. They have benefits of identifying the factors that contribute to lapse risk for any specific person and moment in time. 

<!-- you are scattering the top-down/bottom up thorugh different paragraphs.  It feels disorganized. Is there a better way to organize this? -->
Importantly, the selected features should also predict well among individuals from disadvantaged groups. One of the key benefits of DTx is that they partially address barriers utilizing professional help by providing 24/7/365, affordable, personalized support. They are particularly beneficial to marginalized groups who have low rates of utilizing treatment options due to these treatment barriers. However, they might exacerbate health inequity if embedded algorithms perform relatively worse for less privileged groups. One possible explanation of differential performance across subgroups might stem from the features we feed the algorithms. For example, features derived from a theory-driven approach might be biased towards advantaged groups because they depend on decades of research on White males. The biased features therefore might favor better prediction performance for advantaged groups because they are more robust in predicting their relapse risks. Notably, the differential performance between different groups might also be owing to the under-representation of unprivileged groups in the dataset besides feature selection. The algorithms might sacrifice some prediction accuracy for the minority groups if they are severely underrepresented in the data to ensure overall model performance. As such, it is important to recruit a diverse sample to complete model training. Some statistical resampling strategy might also be used to increase the representation of marginalized groups in the dataset.

<!-- this probably could use a new section heading.  Maybe you want to make better use of section headings thoughout? -->
Recent DTx work has yielded satisfactory performance in predicting lapses with EMA measures. Our group developed an XGBoost machine learning model using self-reported craving, affect, efficacy, risky situations, stressful events, pleasant events to predict alcohol lapses in the next hour, day, or week [@wyantMachineLearningModels2023b]. The surveys were collected up to four times daily for three months. The model achieved exceptional performance when predicting lapses for new individuals, with a mean auROC score of .89, .90 and .93 for the hour-, day-, and week-level model respectively. Global feature importance demonstrated that past alcohol use and future self-efficacy consistently contributed greatly across all models to predict lapses.

Nonetheless, relying on EMA measures for model building is associated with several limitations. First, constantly completing surveys makes it burdensome for real-world DTx use. Although most EMA relevant mental health research demonstrated modest compliance rates, their time windows last from two weeks to three months [@porras-segoviaSmartphonebasedEcologicalMomentary2020; @czyzEcologicalAssessmentDaily2018; @vangenugtenExperiencedBurdenAdherence2020a; @mackesy-amitiFeasibilityEcologicalMomentary2018; @hungSmartphonebasedEcologicalMomentary2016]. The study length is insufficient for real-world DTx use. As extended period of time of app use is anticipated, users' perceived burden of answering surveys is presumably larger [@mogkImplementationWorkflowStrategies2023]. Although minimizing the number of items in the surveys and the frequency of prompting users to complete the surveys might help mitigate the associated burden, it can inevitably reduce the prediction precision and temporal precision of algorithms.
<!--this section seems a bit redundant. You had a long previous section about what good features should look like.  I think its sufficent to highlight the dimenstions that are not optimal for EMA quickly and then move on to your approach for features  -->

Second, decisions regarding what constructs to assess and what items to include to assess these constructs are limited by theory and past data. Including risk factors solely drawn from decades of research on White, male-dominant samples might even exacerbate health disparities when applied to DTx. Further, our current understanding of alcohol relapse precursors is not comprehensive, especially for proximal factors. For example, Marlatt's proposed taxonomy characterizes high-risk situational precursors to alcohol relapse such as social pressure and positive/negative emotional state [@marlattTaxonomyHighriskSituations1996a]. Nonetheless, replication studies have found this theoretical framework to be somewhat unreliable and have low predictive validity of post-treatment outcomes [@lowmanReplicationExtensionMarlatt1996a; @stoutPredictiveValidityMarlatt1996; @kaddenMarlattRelapseTaxonomy1996]. A review study also suggests that current proximal factors are not well-understood in past research due to methodological constraints and a death of "near real-time" data [@mckayConceptualMethodologicalAnalytical2006b].

<!-- new section heading -->
Text sensing technology, which is both feasible and sustainable, represents new opportunities in DTx that might address limitations of the current active reporting approach. Since AUD is a chronic condition requiring ongoing risk monitoring over an extended period, DTx can benefit from SMS sensing because it places a low burden on users and allows for continuous data collecti138on. Studies collecting passive data have demonstrated high acceptability from participants and higher compliance rates compared to active measures [@wyantAcceptabilityPersonalSensing2023a; @beukenhorstUsingSmartphonesReduce2022a]. Further, risk monitoring using SMS sensing is temporally sensitive to fluctuating risks. Analyzing text messages can detect potential triggers in time without actively prompting users to reflect on their feelings at the moment or report their environment.

With the burgeoning of NLP techniques, language analysis is well-equipped with diverse feature engineering tools to have good predictability with temporal specificity for alcohol lapses in new individuals. Some top-down methods might have good performance because they allow researchers to mine previously established robust construct of alcohol lapse precursors. For example, a bag-of-words approach using customized dictionary might allow researchers to mine alcohol-related content from messages such as alcohol cravings. Sentiment analysis can also enable researchers to assess individuals' affect state. Further, some NLP methods follow a bottom-up approach. They might identify new alcohol lapse precursors and are less susceptible to limitations in past research. For example, topic modeling techniques such as Latent Dirichlet Analysis (LDA) and Latent Semantic Analysis (LSA) can examine patterns in SMS messages and identify clusters of topics from the data. Word embeddings approach transforms words into vectors with high dimension space. 

NLP also offers avenues for model interpretation to yield valuable insights into treatment recommendations. Although some feature engineering techniques (e.g., word embeddings) might reveal arbitrary features that is incomprehensible, some can still mine features that can be potentially interpretable (e.g., topic clustering). Assessing their feature importance helps us understand how features contribute to the models (i.e., which features are robust in predicting lapses). For example, global feature importance can identify robust predictors across individuals in predicting lapses. Local feature importance provides insights on what contributes to a lapse for a specific person at a specific time. They can be useful in personalized, just-in-time treatment recommendations.

## Current Study

In this study, we will utilize different NLP techniques to predict lapses from SMS message content. More specifically, we will compare across different feature engineering methods encompassing topic modeling, sentiment analysis, bag-of-words, word embeddings, and customized dictionary. We will evaluate model performance from three aspects: 1) overall model prediction performance in detecting lapses; 2) model interpretability; and 3) performance between advantaged groups vs. disadvantaged groups with regards to race, gender, income and age. 

\newpage

# Approach

## Overview

This study will analyze data collected from 2017-2019 from a larger grant funded by National Institute of Alcohol Abuse and Alcoholism (R01 AA024391). In this proposal, we focus on methods and measures that are relevant to this study.  Additional details on broader methods and the full set of measures collected are discribed elsewhere (see https://osf.io/w5h9y/ and [@wyantMachineLearningModels2023b; @wyantAcceptabilityPersonalSensing2023a]). 

## Participants

Individuals in early recovery from AUD were recruited from Madison and surrounding area via social media platforms (e.g., Facebook), referrals from clinics, and television and radio advertisements. After initial phone screen, interested individuals came in-person to complete a more in-depth screening to determine their eligibility. We documented their demographic information. Inclusion criteria include that participants: 1) must be at least aged 18 or older; 2) must meet criteria for AUD with at least moderate severity (\>four DSM-5 criteria); 3) must be abstinent from alcohol for at least one week and fewer than two months at time of intake; 4) must be able to read and write in English; 5) must be willing to use smartphone and their smartphone is compatible with our study technology. Participants were excluded if they have a lifetime history of severe and persistent mental illness. One hundred sixty-nine participants were eligible and enrolled in the study. After excluding participants who discontinued before the first follow-up session and those with low compliance rates, we have a final sample size of 151 participants.

## Procedures

The study lasted up to three months with five in-person visits (see *Figure 1*). Participants completed an in-person screening visit to determine their eligibility, obtain their informed consent, and collect their demographic information and self-report measures. They then completed an intake session one week later and three follow-up visits afterwards spaced at one-month intervals. During each of the follow-up visits, a research assistant downloaded participants' SMS messages from their phone, verified reports of lapses and queried participants about any additional unreported laspes. Additional self-reported measures were obtained (see https://osf.io/w5h9y/). 

Throughout the course of the study, participants were expected to complete four daily EMAs that asked about their alcohol cravings, risky situations, stressful/pleasant events, etc [@wyantMachineLearningModels2023b]. Notably, in the first item in the EMA survey, participants also reported their past alcohol use. Answer to this item will be used as the predicted outcome (see *Section Alcohol Lapses*). 


::: {#fig-simp}
```{dot}
digraph {

  graph [layout = dot, rankdir = LR];
  node [shape = rectangle];
  
  a[label = "Screening"]
  b[label = "Intake"]
  c [label = "Follow-up 1"]
  d [label = "Follow-up 2"]
  e [label = "Follow-up 3"]
  
  a -> b [label = "1 week", minlen = 1] 
  b -> c [label = "1 month", minlen = 3]
  c -> d [label = "1 month", minlen = 3]
  d -> e [label = "1 month", minlen = 3]

  subgraph {
      rankdir = LR
      
      f [shape = none, margin = 0, labelloc = t,
      label = "demographic information\n"]
      g [shape = none, margin = 0, labelloc = t,
      label = "frequent contact information\n frequent address information"]
      h [shape = none, margin = 0, labelloc = t,
      label = "illicit drug use"]
      i [shape = none, margin = 0, labelloc = t,
      label = "illicit drug use"]
      j [shape = none, margin = 0, labelloc = t,
      label = "self-reported acceptability and burden"]

  }
  
  a -> f [minlen = 0.1, color=none]
  b -> g [minlen = 0.1, color = none]
  c -> h [minlen = 0.1, color = none]
  d -> i [minlen = 0.1, color = none]
  e -> j [minlen = 0.1, color = none]

  
}
```

Flowchart of in-person visits. We obtained participant demographics and alcohol use history from the screening session. SMS messages were downloaded from participant phones at each of the follow-up visit.
:::

## Measures

### Individual Characteristics

We collected participants' individual characteristics including their demographics and their past drinking history during the screening session (see *Table 1*). 

| Log Type            | Measure                                                           |
|:---------------------|:-------------------------------------------------|
| Demographics        | Age                                                               |
|                     | Sex                                                               |
|                     | Race                                                              |
|                     | Ethnicity                                                         |
|                     | Highest Education                                                 |
|                     | Employment Status                                                 |
|                     | Total Personal Gross Income                                       |
|                     | Marital Status                                                    |
|                     | Family Member                                                     |
| Alcohol Use         | Alcohol Use History                                               |
|                     | DSM-5 Checklist for AUD                                           |
|                     | Young Adult Alcohol Problems Test                                 |
|                     | WHO-The Alcohol, Smoking and Substance Involvement Screening Test |

: Participant self-reported measures

### SMS Messages

At each of the follow-up visits, a research assistant downloaded the participants' SMS message logs from their phone. These logs included the message type (incoming vs. outgoing), date and time sent/received, text body, contact name, whether the participants read the text or not, etc. Images and voice texts were excluded from analysis. Both group messages and one-on-one messages were obtained from participants' phones.

Text messages within a 24-hour window (from 4 a.m. to 4 a.m. in the next day) will be grouped together. Incoming messages and outgoing messages will be analyzed independently. Namely, we will have two predictors for each alcohol lapse -- grouped incoming messages and grouped outgoing messages within the 24-hour time window. Each predictor will be referred to as a "document" in the following sections. The documents will then go through pre-processing and feature engineering steps.

### Alcohol Lapses

Participants were prompted up to four times daily to report their recent alcohol use. In the first item of each daily EMA survey, dates and times of any unreported past alcohol use were obtained. Reports of past alcohol use are used as a dichotomous outcome variable (Lapse vs. No Lapse). We will predict alcohol lapses in the next 24-hour window (i.e., next day lapse prediction). Every prediction window will start from 4 a.m. everyday and end 24 hours later.

## Feature Engineering

Text messages will serve as the raw source for all feature engineering.  We will use several natural language processing techniques to transform SMS messages into machine-interpretable data and input them into machine learning algorithms. The methods we consider include: 1) topic modeling; 2) sentiment analysis; 3) n-gram approach; 4) dictionary approaches (LIWC and customized alcohol-relevant dictionaries); and 5) word embeddings. Each feature engineering technique will be evaluated separately. 

Note that these feature engineering techniques encompass both top-down approaches and bottom-up approaches. Topic modeling, n-grams, and word embeddings are exemplary empirically-driven methods. Sentiment analysis aligns with concepts in affect science. LIWC relies on theories broadly in psycho-social research, and customized dictionary can be refined to narrower domain knowledge specific to addiction science [@tausczikPsychologicalMeaningWords2010a]. Features built from these top-down approaches may be more interpretable and can map on to current interventions. 

### Topic Modeling

Topic modeling is an unsupervised machine learning method to identify clusters of topics in a body of text. We will tokenize documents into tokens of lower-case words and remove stop words (i.e., common words without significant meaning) and punctuations. We will also perform stemming to transform the words into their root form. We will further apply the cleaned tokens into one of the most popular topic modeling technique -- Latent Dirichlet Analysis (LDA). LDA unravels the hidden structure in the relationships between words in a document and groups similar words into topics. It assumes that different documents (i.e., SMS messages) have same topic clusters but with different distribution. As such, different topic clusters might have common words.

### Sentiment Analysis

Research has found that positive/negative emotional state to be associated with increased alcohol relapse risks [@mckayConceptualMethodologicalAnalytical2006b; @mckayStudiesFactorsRelapse1999a; @brownCharacteristicsRelapseFollowing1989]. Sentiment Analysis infers the emotional underpinning of texts. We will extract both emotional valence (i.e., positive, neutral, and negative emotional tone) and eight basic emotion categories (e.g., anger, fear, anticipation, trust, surprise, sadness, joy, and disgust) from SMS messages. We will perform tokenization, stemming, and removal of stop words. We will then assign each document a score in those ten categories by summing sentiment content of all tokens in that message.

### N-grams Approach

A bag-of-words approach represents word occurrences inside a document. We will first tokenize documents into one-gram and two-gram words. Then we will stem the n-grams and remove stop words. We will then analyze these n-grams based on their term frequency (tf), and a combination of term frequency and inverse document frequency (tf-idf).

Tf indicates the frequency of the n-grams in each individual text relative to that text length. We will also further utilize combination of both tf and idf to calculate tf-idf, which indicates word importance inside a document (see below formula). This scoring method has the advantage of highlighting the importance of a word to a document in a collection of documents. It has important implications in analyzing SMS messages so that we have a better understanding of the robustness of a certain word to a single message across all text messages that the participants sent. The idf score minimizes weights of words that are commonly used across all messages and can highlight words that contain important information.

$$
\text{tf} = \frac{n_{terms\ in\ document}}{n_{terms}}
$$
$$
\text{idf} = \ln(\frac{n_{documents}}{n_{documents\ containing\ term}})
$$
$$
\text{tf-idf} = tf * idf
$$


### Dictionary Approach

This study will also expand above bags-of-word approach by using customized dictionaries built upon the LIWC dictionary [@pennebakerDevelopmentPsychometricProperties2015a] and compute score by counting frequency of words that belong to each category. In the pre-processing step, we will tokenize the document into lower case words and remove punctuations. We will not remove any stop words. LIWC aligns with the current alcohol relapse risk factor literature in that it examines psychometric properties including cognitive state and social processes [@brownCharacteristicsRelapseFollowing1989; @mckayStudiesFactorsRelapse1999a; @mckayStudiesFactorsRelapse1999a]. In addition to these linguistic categories, we will also include customized alcohol-related category as predictors as previous research has found them to be robust indicators of alcohol lapses [@mckayStudiesFactorsRelapse1999a; @korlakuntaReasonsRelapsePatients2012]. We will compute the relative frequency of each token that matches the dictionary normalized by the total number of tokens in the document.

### Word Embeddings

Word embeddings are vectors that represent relationships of words within a document in a lower-dimension. We will tokenize document into lower-case words, stem them and remove stop words. We will use the pre-trained Bidirectional Encoder Representations from Transformers (BERT)[@devlinBERTPretrainingDeep2018] to transform documents into such machine-readable vectors. It is capable of capturing embedded semantic structure within a neural network architecture.They take into account the context of where a word is (i.e., word tokens before and after the target word). It is also pre-trained on a massive dataset, which allows the model to learn a wide range of patterns and structures. Independently, we will also use Global Vectors for Word Representation (GloVe) to transform text into word embeddings. This method constructs a word co-occurrence matrix and factorizes it to generate word vectors. 

## Candidate Machine Learning Algorithms

We consider a range of candidate algorithms that vary with regard to their model complexity, model assumptions, and training speed. Candidate algorithms that will be used include glmnet (penalized, parametric linear model), random forest (RF), and XGBoost. 

## Model Training and Performance Evaluation

We will perform a grouped, nested cross-validation to perform hyperparameter tuning and select the best model configuration. The dataset will be participant-grouped so that each individual will be assigned to either held-in or held-out set to avoid bias of predicting participants' lapses using their own data. The nested cross-validation method uses two nested loops to divide folds. In the inner loop, held-out folds are used as a validation set for model selection. In the outer loop, held-out folds are utilized as a test set for model evaluation. More specifically, we will use one repeat of 10-fold cross-validation in the inner loop for model selection and 3 repeats of 10-fold cross-validation in outer loop for model evaluation.

The primary performance metrics to select the best model configuration and evaluate the model performance on the test sets will be auROC. auROC computes the area under the ROC curve which demonstrates the trade-off between sensitivity and specificity across all possible thresholds. Values between .70 and .80 are considered fair, values between .80 and .90 are considered good, and values above .90 are considered excellent. We will report the median auROCs for the 30 held-out folds. 

## Feature Importance

We will also calculate SHAP values to interpret the results. SHAP is a game theory based method to explain how each feature influences the model output [@lundbergUnifiedApproachInterpreting2017]. It assigns importance to each feature, where a positive feature importance positively affects the model output. This methodology can be applied to any machine learning algorithm and can increase model transparency and interpretability. We calculate the local Shapley value for each feature in each observation. We also further compute global Shapley values by averaging the absolute value of local Shapley values across all observations.

## Model Comparison and Algorithmic Bias

We will further perform a Bayesian hierarchical generalized linear model to estimate the posterior probability (i.e., the likelihood of achieving the results given out data) distributions of the auROCs. We will regress the 30 auROCs from the held-out test set as a function of feature engineering technique (a total of 10 comparisons for the five NLP methods). The two random intercepts in the models include the repeat and the fold within repeat. We will report the 95% CIs for our models' auROCs and determine if they include .5 (chance performance). We will also report the 95% CI for the differences in performance with regard to Bayesian comparison. If this CI does not include 0, we can conclude that the feature engineering technique yields better model performance than the other.

A subset of individual characteristic measures will be used to evaluate model fairness on subgroups . We will compare model performance among each sex, racial, age and income subgruops because the populations face increased barriers obtaining AUD treatments. Stigma among older populations and wome, and economic hardship in racial minority groups can all contribute to low treatment-seeking and alcohol treatment completion [@dibartoloAlcoholUseDisorder2017; @jacobsonRacialDisparitiesCompletion2007; @mayBarriersTreatmentAlcohol2019]. We will perform a Bayesian hierarchical generalized linear model that regresses the auROCs from the 30 held-out test set as a function of group membership (privileged group vs. unprivileged group in each of above individual characteristics). We will report the 95% CI for model performance differences and examine if they include 0.

\newpage

# References
