---
format: pdf
margin-left: 60pt
margin-right: 60pt
margin-bottom: 60pt
margin-top: 60pt
---

Dear Dr. Mitra,

We are pleased to submit a revised version of our manuscript "Evaluating Cellular Communication Sensing for Lapse Risk Prediction During Early Recovery from Alcohol Use Disorder." We thank the reviewers for their thoughtful commentary. We have included detailed responses to each of the editor's and reviewers' concerns beginning on the following page.

If we can provide any additional information that can be of assistance, please do not hesitate to ask. Thank you in advance for your consideration.

Sincerely,    

Kendra Wyant, Jiachen Yu, & John J. Curtin


---


Below, we delineate the reviewers’ and editor’s questions, concerns, and requests regarding our original submission, and we detail the ways in which we have addressed each item. All comments have been copied verbatim to avoid misinterpretation.


## Editor

### 1. Please ensure that your manuscript meets PLOS ONE's style requirements, including those for file naming.
We have reviewed the PLOS One's style requirements and updated our manuscript accordingly. We have also ensured that our file names meet the requirements.
<!--Double check prior to resubmission: https://journals.plos.org/plosone/s/file?id=wjVg/PLOSOne_formatting_sample_main_body.pdf and  https://journals.plos.org/plosone/s/file?id=ba62/PLOSOne_formatting_sample_title_authors_affiliations.pdf-->


### 2. Please note that PLOS One has specific guidelines on code sharing for submissions in which author-generated code underpins the findings in the manuscript. In these cases, we expect all author-generated code to be made available without restrictions upon publication of the work. Please review our guidelines at https://journals.plos.org/plosone/s/materials-and-software-sharing#loc-sharing-code and ensure that your code is shared in a way that follows best practice and facilitates reproducibility and reuse.
We have uploaded a copy of our code to our OSF page following the recommended guidelines for code sharing. This OSF page is also referenced in our manuscript.

### 3. PLOS requires an ORCID iD for the corresponding author in Editorial Manager on papers submitted after December 6th, 2016. Please ensure that you have an ORCID iD and that it is validated in Editorial Manager. To do this, go to ‘Update my Information’ (in the upper left-hand corner of the main menu), and click on the Fetch/Validate link next to the ORCID field. This will take you to the ORCID site and allow you to create a new iD or authenticate a pre-existing iD in Editorial Manager.
We have ensured the ORCID ID for the corresponding author is entered and validated. 
<!--confirm with John is ORCID is entered and validated-->


### 4. Please include a copy of Table 1 which you refer to in your text on page 9
We ensured Table 1 was included in the manuscript. 

### 5. If the reviewer comments include a recommendation to cite specific previously published works, please review and evaluate these publications to determine whether they are relevant and should be cited. There is no requirement to cite these works unless the editor has indicated otherwise. 
N/A


## Reviewer 1

### 1. Overall, the paper lacks clear hypotheses on how authors expected, for instance individual number of social contacts, or a preference for certain types of social contacts (with people who drink, know about abstinence goals etc.), or change in types of contacts to affect individual capability of keeping abstinence goals. Exploring communication patterns based on what is known about the role of social contacts or lack thereof in addiction and comorbid psychiatric disorders would better explain the rationale for the study.
We have added a paragraph to the introduction that synthesizes the literature on the relationship between social networks and lapse. Specifically, we highlight key findings that map onto the constructs we are evaluating (e.g., interactions with people supportive and unsupportive of one's recovery goals). 


### 2. Continued, compulsive intake of alcohol is a feature of addiction. Drinking every day does not necessarily mean that the person does not have abstinence as a goal. It may just as well reflect severity of the condition. Therefore, excluding an individual based on an assumption (not defined in the exclusion criteria) is methodologically problematic. It could both affect results and limit generalizability.
We revisited our exclusion criteria and found that the one participant removed for continued drinking did not provide any cellular communication data at their first month follow-up visit. We could therefore not include them in our analyses. 
We have updated our exclusion criteria accordingly: We enrolled 169 participants. Of these, 151 completed the first follow-up visit where the first cellular communication log download occurred. We excluded data from seven participants due to poor compliance providing communication data (i.e., deleting all of their voice calls and text messages prior to the download or not providing context information about important contacts). The final analytic sample included 144 participants. 

### 3. Handling of missing data is insufficiently explained. In the addiction field data is seldom missing at random. To the contrary, missing data is often associated with relapse. Is is also more common in those with more severe addictive disorders. Author describe that missing data was imputed. Please specify how data was imputed. Describe which variables were imputed and what methods were used. Was there any association between missing variables and problem severity (ex symptom count of reported alcohol use).
We previously included an imputation step in our data pre-processing pipeline. However, we have since removed this as it was unnecessary. Our data set is unique in that we had no missing data. If no cellular communication data were observed during a feature scoring epoch (i.e., the individual had no calls or text messages) that feature was scored 0. We also had no missing data across baseline measures included in our models. We now make this more clear in our methods. That being said, we appreciate the point this reviewer makes. It is still possible that participants were deleting cellular communications in a non-random manner. We acknowledge this now in the discussion as a potential limitation. 

### 4. The size of the explored cohort is limited (<150 individuals). Use of cellular communication varies widely across sex, age, possibly on whether one is employed or not (i.e. busy during the day) or not etc. The social function of different types of cellular communication is also expected to vary widely. This is mentioned in the discussion, but authors are also encouraged to reflect on whether lack of a significant association could be due to type 2 error?
We now make more clearly in the methods and discussion how our study design can capture interactions between demographics (and other baseline measures) and cellular communications. Specifically, two of the three algorithms we considered (Random forest and XGBoost) can natively handle interactions. Thus, if there were strong interactions between sex, age, or employment status and cellular communication features, these models would have emerged as having the top performance. To the contrary, our best performing model used a linear elastic net algorithm. This suggests the relationship between features are primarily additive as opposed to interactive. 

We also now mention our sample size as a potential limitation and discuss implications of this in our discussion.

### 5. Individual characteristics, including personality traits, potential comorbid psychiatric conditions/ symptoms such as anxiety or depression (if available) would be informative to add to the baseline and follow up measures and potentially inform changes in communication patterns.
We appreciate the suggestion and have added psychiatric and personality features to our model. Specifically, we now include three higher order dimensions of personality from the Multidimensional Personality Questionnaire Brief Form (positive emotionality, negative emotionality, and constraint) and three broad psychiatric conditions from the Depression Anxiety Stress Scale (Depression, Anxiety, and stress).


### 6. Isolating oneself, to a degree that is discernable in social behavior as part of increased anxiety and depression, craving may take longer than two weeks. Could authors explain how the different time windows performed and were interpreted? Could changes be associated with traits such as impulsivity, low mood, anxiety? Are data on these aspects available. Have interactions and potential mediation been explored?
In our study, the longest scoring epoch was one week. We agree that experiences such as craving and depression may take longer than one week to affect downstream changes in social behavior. However, these constructs were not modeled as time‑varying features in our analyses. Instead, communication features were calculated over scoring epochs that roll forward day by day, independent of craving or depressive symptoms. Thus, our one week scoring epochs would be calculated both during, immediately after, and much later than a single episode of craving.

It is, however, possible that scoring features over longer epochs (e.g., two weeks or one month) could better capture slower‑evolving processes that could be seen in communication data, such as a slowly shrinking social circle; however, because participants contributed, at most, three months of data, longer epochs would substantially reduce the number of usable observations. We therefore felt it would be inappropriate to use scoring epochs of that length given the available data. We acknowledge this as a limitation now in our discussion section.

In response to the reviewer’s question regarding individual differences, We added baseline psychiatric and personality measures per the reviewer's request. If changes in traits such as depression and anxiety (features added to our model) were associated with changes in communication features we would expect models that natively handle interactions (XGBoost and random forest) to outperform the linear elastic net model. Our full model did not retain any of these additional features and our best performing model used an elastic net suggesting there were not large interactions between these sets of features and an additive model more closely resembled the true data generating process. 

### 7. Goal of abstinence, abstinence confidence tend to increase with abstinence time - the longer the abstinence the higher the continued goal of abstinence and the confidence. Was data on abstinence time available? Could these predictors be considered as time varying or maybe consider interaction terms?
We agree that abstinence duration is often associated with increases in both abstinence confidence and commitment to continued abstinence. We did have a baseline measure of abstinence time; however, maintaining an accurate measure over the course of the study would have required updating abstinence duration based on reported lapses collected via daily EMA. Similarly, we collected time‑varying information on abstinence confidence and abstinence goals through EMA assessments.

For the goals of this study, however, we intentionally restricted time‑varying predictors to features derived from cellular communication data. EMA data were used exclusively to generate outcome labels (lapse vs. no lapse), rather than as dynamic predictors in the models. Incorporating abstinence duration, confidence, or goal as time‑varying features would therefore have expanded the scope of the analysis beyond cellular communication sensing features and was not pursued in the current work.

### 8. Results reflect what is already known about craving and negative affect being positively associated with relapse risk. However, communication with someone who doesn’t know about recovery is a novel finding and needs to be better explained. This association would be interesting to explore further.
We agree this is an interesting finding. Unfortunately, with our current models we are not able to speak more about this feature beyond its positive association with lapse risk (i.e., more frequent contacts with people who do not know the individual is in recovery increase lapse risk). We highlight this as an unexpected finding worth exploring more in future research in our discussion section.

### 9. Social isolation and lack of significant social support are important factors associated with recovery. Number of contacts varied widely (between 2 and >100!) in the population. I would expect increased social isolation (less communication, changes in communication pattern) in a the more social individuals (who have many contacts) to be a sign of increased depression or anxiety – which in turn could be associated with relapse. Could authors describe patterns of social contacts and change over time more clearly? Was number of contacts considered? Was change in communication, depending on number of contacts of any relevance?
We agree that changes in communication may be more or less risky for individuals depending on the number of contacts that change is coming from. While total number of contacts varied widely across participants, we did not include absolute number of contacts as a predictive feature. Doing so would have required using information not yet observed at the prediction time point (e.g., the total number of unique contacts communicated with over the full study period), and would introduce leakage from future data into the model.

To address this concern, we included both raw and difference scores of all sensing features. Difference scores allow us to create a feature that essentially compares the number of contacts (or any other communication feature) during a given scoring epoch to that individual's typical number of contacts (across all study days up until the prediction time point). This allowed us to capture changes in communication relative to an individual's typical level of communication without using information from the future. We have updated the feature engineering section of the manuscript to more clearly describe these features. 


## Reviewer 2

### 1. Please include number of participants excluded after recruitment, the missing data rates, data preprocessing steps for the study.
We have included the requested information in the methods section. We also provide the excerpts from the manuscript here for easy reference. 

We enrolled 169 participants. Of these, 151 completed the first follow-up visit where the first cellular communication log download occurred. We excluded data from seven participants due to poor compliance providing communication data (i.e., deleting all voice calls and text messages prior to the download or not providing context information about important contacts). The final analytic sample included 144 participants.

We had no missing data across baseline measures of demographics, alcohol use characteristics, and psychiatric and personality characteristics. If no cellular communication data were observed during a feature scoring epoch that feature was scored 0, thus there were also no missing data among cellular communication features. Other feature engineering steps performed during cross-validation included standardizing all features and removing zero and near-zero variance features as determined from held-in data (code for our full data pre-processing pipeline is available on our OSF page [([https://osf.io/wgpz9/](https://osf.io/wgpz9/)]). 

### 2. Some of the methodological concerns include - all the recruitment occurring from one Geographical location (Madison, WI) only, which limits generalizability, self reported DSM-5 symptoms for Alcohol use disorder rather than a structured clinical interview- patients don't have the clinical knowledge to detect symptom's accurately and reliably, Smartphone requirement introduces a selection bias.
We now comment on these limitations in our discussion section.

### 3. Ecological Momentary assessment compliance was not reported- which could introduce label misclassification. Alcohol use reporting may suffer from recall bias and social desirability bias.
We now include adherence rates to our EMA protocol. Specifically, participants demonstrated good adherence to our 4X daily EMA protocol (mean adherence = 78%) and provided at least one EMA on 95% of study days.

### 4. The method could have been strengthened by explaining how 192 participants is sufficient for power of study- in the setting of machine learning.
We appreciate this suggestion for strengthening our method justification. We now comment on this in the discussion.
