---
format: pdf
margin-left: 60pt
margin-right: 60pt
margin-bottom: 60pt
margin-top: 60pt
---

Dear PLOS One Editorial Team,  

We are pleased to submit our manuscript titled **"Evaluating Cellular Communication Sensing for Lapse Risk Prediction During Early Recovery from Alcohol Use Disorder: A Longitudinal Observational Study"** for consideration as a **Research Article** in *PLOS One*. 

In this study, we evaluated cellular communication data as a personal sensing method for predicting next-day lapses back to alcohol use among individuals in early recovery from Alcohol Use Disorder. Using a 3 month longitudinal observational design and machine learning methods, we found that dynamic sensing of cellular communications appeared to capture risk-relevant signal for lapses back to alcohol use. However, these features did not provide incremental predictive value beyond static baseline measures of demographics and alcohol use history.

Nevertheless, null findings are critical for guiding the responsible development of personal sensing technologies. Substantial resources are being invested in passive sensing approaches to monitor changes in mental health symptoms. Our results highlight potential limitations of cellular communication sensing that may inform prioritization of sensing methods with the greatest likelihood of clinical utility. In the Discussion, we describe limitations inherent to cellular communication sensing, including data sparsity and platform constraints, and outline alternative directions for future research in personal sensing and lapse prediction.

We believe this manuscript is well suited to *PLOS One* given the journal’s focus on rigourous empirical methods and transparent and responsible reporting of both null and significant findings. The open-access nature of the journal will also facilitate broad dissemination of these findings to researchers, clinicians, and developers working in digital mental health and addiction science.

This manuscript has not been published and is not under consideration elsewhere. All authors have approved the submitted version and agree to its submission to *PLOS One*.


Suggested Academic Editors:

1. Ethan Moitra
2. David T. Zhu



Thank you for your consideration. Please do not hesitate to contact us if any additional information would be helpful. We look forward to hearing from you regarding this manuscript.


Sincerely,    
Kendra Wyant, Jiachen Yu & John J. Curtin

