---
title: "Performance plots"
author: "John Curtin & Coco"
date: "`r lubridate::today()`"
output: 
  html_document:
    toc: true 
    toc_depth: 4
format:
  html:
    embed-resources: true
params:
  study: "messages"
  version: "v1"
  cv: "nested_1_x_10_3_x_10"
  algorithms: "xgboost"   # "all" or name of specific algorithm
editor_options: 
  chunk_output_type: console
---

## Code status

Complete for use in GPS study as of 10/2024.

## Notes

Generates auROC plot.

## Set Up


### Study parameters
```{r}
study <- params$study
cv <- params$cv
algorithms <- params$algorithms
version <- params$version
```

### Defaults
```{r}
#| message: false
#| warning: false

# handle conflicts
options(conflicts.policy = "depends.ok")
devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/fun_ml.R?raw=true")
tidymodels_conflictRules()

knitr::opts_chunk$set(attr.output='style="max-height: 500px;"')

options(tibble.width = Inf)
options(tibble.print_max = Inf)
```

### Packages for script
```{r}
#| message: false
#| warning: false

library(tidyverse)
library(tidyposterior)
library(yardstick)

theme_set(theme_classic())

devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/format_path.R?raw=true")
```


### Absolute paths
```{r}
path_models <- format_path(str_c("studydata/risk/models/", study))
```

> CP these are I think raw probabilities not beta -- issue?

```{r}
probs <- # read_csv(here::here(path_models, str_c("inner_metrics_", version, "_", cv, ".csv"))) |> 
  read_rds(here::here(path_models, str_c("inner_preds_", version, "_", cv, ".rds"))) |> 
  #pivot_longer(cols = starts_with("prob"), 
               #names_to = "method", 
               #values_to = ".pred_Lapse") |>
  glimpse()
```

```{r}
# CY: confusion over x and y axis

# roc_data <- probs |> 
#   roc_curve(prob_raw, truth = label)
#   
# roc_data |>
#   mutate(sensitivity = round(sensitivity, 4),
#          specificity = round(specificity, 4)) |>
#   group_by(sensitivity, specificity) |> 
#   summarise(.threshold = mean(.threshold)) |> 
#   ggplot(aes(x = 1 - specificity, y = sensitivity, color = .threshold)) +
#   geom_path(linewidth = 1) +
#   geom_abline(lty = 3) +
#   coord_fixed(xlim = c(0, 1), ylim = c(0, 1)) +
#   labs(x = "Specificity",
#        y = "Sensitivity") +
#   scale_x_continuous(breaks = seq(0,1,.25),
#     labels = sprintf("%.2f", seq(1,0,-.25))) +
#   scale_color_gradient(low="blue", high = "red") +
#   theme(axis.text = element_text(size = rel(1.50)), 
#         axis.title = element_text(size = rel(1.75)))
```

## Plots

```{r}
#| label: fig-auroc
#| fig-cap: "auROC Plot"
#| fig-width: 3.5
#| fig-height: 2.5

tpfp_data <- probs |> 
  roc_curve(prob_raw, truth = label)
  
tpfp_data |>
  mutate(tp = round(sensitivity, 4),
         fp = round(1 - specificity, 4)) |>
  group_by(tp, fp) |> 
  summarise(.threshold = mean(.threshold)) |> 
  ggplot(aes(x = fp, y = tp, color = .threshold)) +
  geom_path(linewidth = 1) +
  geom_abline(lty = 3) +
  coord_fixed(xlim = c(0, 1), ylim = c(0, 1)) +
  labs(x = "False Positive Rate",
       y = "True Positive Rate") +
  scale_x_continuous(breaks = seq(0,1,.25),
    labels = sprintf("%.2f", seq(1,0,-.25))) +
  scale_color_gradient(low="blue", high = "red") #+
  # theme(axis.text = element_text(size = rel(1.50)), 
  #       axis.title = element_text(size = rel(1.75)))
```

```{r}
aurocs <- probs |> 
  group_by(inner_split_num, outer_split_num) |> 
  summarize(auroc = roc_auc_vec(truth = label, estimate = prob_raw))
```

histogram of aurocs
```{r}
#| label: fig-auroc_hist
#| fig-cap: "Distribution of auROCs across 300 inner folds"
#| fig-width: 3.5
#| fig-height: 2.5

aurocs |> 
  ggplot(aes(x = auroc)) +
  geom_histogram(fill = "#97C4C5") +
  geom_vline(xintercept = median(aurocs$auroc), linetype = "dashed", color = "red")
```

## Posterior Distribution

```{r}
pp <- aurocs |>
    select(outer_split_num, inner_split_num, auroc) |> 
    rename(id = outer_split_num,
           id2 = inner_split_num) |> 
    perf_mod(formula = statistic ~ 1 + (1 | id/id2),
             # prior_intercept = rstanarm::student_t(autoscale = TRUE),
             # prior = rstanarm::student_t(autoscale = TRUE),
             # transform = tidyposterior::logit_trans,  # for skewed & bounded AUC
             iter = 13000, chains = 4,
             adapt_delta = .99999999,
             # cores = 4, seed = 12345,
             family = gaussian)
```

```{r}
#| label: fig-auroc_posterior
#| fig-cap: "Posterior Distribution of auROC scores"
#| fig-width: 3.5
#| fig-height: 2.5

pp_tidy <- pp |> 
  tidy(seed = 123)

ci_day <- pp_tidy |> 
  summary() |> 
  mutate(y = 30)

# vertical line for the median
pp_tidy |> 
  ggplot(aes(x = posterior)) + 
  geom_density(color = c("#80B1D3"), fill = c("#B3CFE8"), alpha = 1) +
  geom_segment(mapping = aes(y = y, yend = y, x = lower, xend = upper), color = c("#80B1D3"),
                data = ci_day) +
  ylab("Posterior Probability Density") +
  xlab("Area Under ROC Curve")
```

Add in curves for every outer fold.
```{r}
# roc_folds <- probs |> 
#   nest(.by = outer_split_num, .key = "preds") |> 
#   mutate(roc = map(preds, \(preds) roc_curve(preds, prob, 
#                                              truth = truth)))
# 
# fig_roc_folds <- roc_data |>   # plot region from full concatenated data
#   ggplot(aes(x = 1 - specificity, y = sensitivity)) + 
#   geom_abline(lty = 3) +
#   coord_fixed(xlim = c(0, 1), ylim = c(0, 1)) +
#   labs(x = "Specificity",
#        y = "Sensitivity") +
#   scale_x_continuous(breaks = seq(0,1,.25),
#     labels = sprintf("%.2f", seq(1,0,-.25))) +
#   theme(axis.title.x=element_blank(),
#         axis.text.x=element_blank(),
#         axis.ticks.x=element_blank())
#   
# for (i in 1:nrow(roc_folds)) {
#   fig_roc_folds <- fig_roc_folds +
#      geom_path(data = roc_folds$roc[[i]],
#                mapping = aes(x = 1 - specificity, y = sensitivity),
#                color = "gray")
# }
# 
# roc_data_smooth <- roc_data |> mutate(sensitivity = round(sensitivity, 4),
#                                       specificity = round(specificity, 4)) |>
#   group_by(sensitivity, specificity) |> 
#   summarise(.threshold = mean(.threshold)) 
# 
# #add full concatenated curve
# fig_roc_folds +
#      geom_path(data = roc_data_smooth,
#                mapping = aes(x = 1 - specificity, y = sensitivity, color = .threshold),
#                linewidth = 2) +
#     scale_color_gradient(low="blue", high="red")
```