---
title: "Make LIWC features"
author: "Coco Yu"
date: "`r lubridate::today()`"
format: 
  html:
    toc: true 
    toc_depth: 4
    embed-resources: true
editor_options: 
  chunk_output_type: console
---

## Setup

Chunk Defaults
```{r}
knitr::opts_chunk$set(attr.output='style="max-height: 500px;"')
```

Conflicts
```{r}
options(conflicts.policy = "depends.ok")
```

```{r}
library(tidyverse)
library(kableExtra, exclude = "group_rows")
library(lubridate)
library(janitor, include.only = c("tabyl", "clean_names"))
library(here, include.only = c("here"))
```

Source Functions
```{r}
devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/format_path.R?raw=true")
devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/fun_eda.R?raw=true")
```

Absolute Paths 
```{r}
path_messages <- format_path(str_c("studydata/risk/data_processed/messages"))
```


## Clean LIWC Results and Engineer Features

read in lapse labels
```{r}
labels <- read_csv(here(path_messages, "lapses.csv"), col_types = cols()) |> 
  mutate(day_start = as_datetime(day_start, tz = "America/Chicago"),
         day_end = as_datetime(day_end, tz = "America/Chicago"))
```

```{r}
clean_features <- function(window){

  # read in data
  data <- read_csv(
    here(path_messages, str_c("liwc/liwc_", window, ".csv")),
    col_types = cols()
  ) |> 
  janitor::clean_names()

  # remove unnecessary columns
  data <- data |> 
    select(
      -day_start, -day_end, -address, -contact_type, -date, -type, -msg_type,
      -phone_type, -column_id, -segment, -emoji
    )
  
  # normalize liwc scores
  data <- data |> 
    mutate(across(
      -c(subid, lapse, pred_onset, text, wc, wps, analytic, clout, authentic, tone),
      ~ (. * wc / 100) / sqrt(wc)
    ))

  # create new columns
  data <- data |> 
    group_by(subid, pred_onset, lapse) |> 
    summarize(across(
      -text,
      list(
        median = ~ median(., na.rm = TRUE),
        q_10 = ~ quantile(., 0.1, na.rm = TRUE),
        q_90 = ~ quantile(., 0.9, na.rm = TRUE)
      ),
      .names = str_c(window, "_{.col}_{.fn}")
    ),
    .groups = "drop")
  
  # merge with lapse labels
  data <- data |> 
    full_join(
      labels |> 
        mutate(pred_onset = day_start - days(3)),
      by = c("subid", "pred_onset", "lapse")
    ) |> 
    select(-day_start, -day_end)
}
```



## EDA

look at means, median, sd and min/max
```{r}

```

