---
title: "Make Lapse Labels"
author: "Coco Yu"
date: "`r lubridate::today()`"
format: 
  html:
    toc: true 
    toc_depth: 4
    embed-resources: true
editor_options: 
  chunk_output_type: console
---

## Code Status

## Setup

Chunk Defaults
```{r}
knitr::opts_chunk$set(attr.output='style="max-height: 500px;"')
```

Conflicts
```{r}
options(conflicts.policy = "depends.ok")
```

```{r}
library(tidyverse)
library(kableExtra, exclude = "group_rows")
library(lubridate)
library(janitor, include.only = c("tabyl", "clean_names"))
library(here, include.only = c("here"))
```

Source Functions
```{r}
devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/format_path.R?raw=true")
devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/fun_eda.R?raw=true")
devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/fun_plots.R?raw=true")
```

Absolute Paths 
```{r}
path_shared <- format_path(str_c("studydata/risk/data_processed/shared"))
path_messages <- format_path(str_c("studydata/risk/data_processed/messages"))
```

## Read in Data

need further cleaning on lapses: for now, NA if NA in start_time
```{r}
visit_dates <- read_csv(here(path_shared, "visit_dates.csv"),
                        col_types = cols(subid = "d", start_study = "c", 
                                         end_study = "c")) |> 
  mutate(start_study = as_datetime(start_study, tz = "America/Chicago"),
         end_study = as_datetime(end_study, tz = "America/Chicago")) |> 
  select(subid, start_study, end_study) |> 
  glimpse()

lapses <- read_csv(here(path_shared, "lapses_day.csv"),
                   col_types = cols(subid = "d", exclude = "c",
                                    lapse_start_date = "c", 
                                    lapse_start_time = "c",
                                    lapse_end_date = "c",
                                    lapse_end_time = "c")) |> 
  mutate(lapse_start = as_datetime(lapse_start, tz = "America/Chicago")) |> 
  filter(exclude != "DELETE") |>
  glimpse()
```


check participant duration on study
```{r}
visit_dates <- visit_dates |> 
  mutate(time_on_study = as.numeric(end_study - start_study) / 86400) |> 
  glimpse()

visit_dates <- visit_dates |> 
  filter(time_on_study > 1) |> 
  select(-time_on_study) |> 
  glimpse()
```

```{r}
labels <- visit_dates |> 
  rowwise() |>
  mutate(lapse_onset = list(seq.POSIXt(start_study + days(1), end_study, by = "day"))) |> 
  unnest(lapse_onset) |>
  mutate(lapse_onset = update(lapse_onset, hour = 4, minute = 0)) |> 
  select(subid, lapse_onset) |> 
  glimpse()
```

clean up lapse start
```{r}
lapses <- lapses |> 
  mutate(
    lapse_end_date = if_else(is.na(lapse_end_date), 
                             format(mdy(lapse_start_date) + days(1), "%m/%d/%Y"),
                             lapse_end_date),
    lapse_start_time = if_else(is.na(lapse_start_time), "20:00", lapse_start_time),
    lapse_end_time = if_else(is.na(lapse_end_time), "2:00", lapse_end_time),
    lapse_start = mdy_hm(paste(lapse_start_date, lapse_start_time)),
    lapse_start = force_tz(lapse_start, tzone = ema_1_6),
    lapse_start = as_datetime(lapse_start, tz = "America/Chicago"),
    lapse_end = mdy_hm(paste(lapse_end_date, lapse_end_time)),
    lapse_end = force_tz(lapse_end, tzone = ema_1_6),
    lapse_end = as_datetime(lapse_end, tz = "America/Chicago")
    ) |> 
  glimpse()

any(is.na(lapses$lapse_start))
any(is.na(lapses$lapse_end))
```

join lapses to labels\

expand rows for lapses if multiple days
```{r}
lapses <- lapses |> 
  filter(duration > 40) |> 
  rowwise() |> 
  mutate(lapse_start = list(seq.POSIXt(lapse_start, lapse_end + days(1), by = "day"))) |> 
  unnest(lapse_start) |> 
  bind_rows(lapses) |>
  glimpse()
```


```{r}
labels <- labels |> 
  full_join(lapses |> select(subid, lapse_start, exclude), by = "subid") |> 
  mutate(
    lapse_end = lapse_onset + days(1),
    label = if_else(
      exclude == "TRUE", NA_character_,
      if_else(lapse_start >= lapse_onset & lapse_start <= lapse_end,
              "yes", "no", missing = "no"),
      missing = "no"
    )
  ) |> 
  group_by(subid, lapse_onset) |> 
  summarize(label = if_else(any(label == "yes"), "yes", "no")) |> 
  ungroup() |> 
  glimpse()
```

## EDA
```{r}
labels |> 
  tabyl(label)

labels |> 
  tabyl(subid, label)
```

## Write-out csv

```{r}
labels |> 
  write_csv(here(path_messages, "lapses.csv"))
```