---
title: "shaps"
author: "Claire & Coco"
date: "`r lubridate::today()`"
output: 
  html_document:
    toc: true 
    toc_depth: 4
format:
  html:
    embed-resources: true
params:
  study: "messages"
  version: "v1"
  cv: "nested_1_x_10_3_x_10"
  algorithms: "xgboost"   # "all" or name of specific algorithm
editor_options: 
  chunk_output_type: console
---

# Set up environment

```{r}
study <- params$study
cv <- params$cv
algorithms <- params$algorithms
version <- params$version
```

```{r}
library(tidyverse)
theme_set(theme_classic()) 
devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/format_path.R?raw=true",
                     sha1 = "a58e57da996d1b70bb9a5b58241325d6fd78890f")
path_models <- format_path(str_c("studydata/risk/models/", study))
#path_mak <- "mak/risk"
```

```{r}
shaps_grp <- read_rds(file.path(path_models, str_c("inner_shapsgrp_", 
                                           version, "_", cv, ".rds"))) |>

  glimpse()
```

```{r}
shaps <- shaps_grp |>
  group_by(variable_grp) |> 
  summarize(mean_value = (mean(abs(value)))) |> 
  mutate(group = reorder(variable_grp, mean_value)) |> 
  arrange(desc(mean_value))
```

```{r}
#| label: fig-shaps
#| fig-cap: "Shapley Value"

shaps |>
  head(30) |> 
  ggplot() +
  geom_bar(aes(x = group, y = mean_value), stat = "identity", fill = "#af1f21") +
  ylab("Mean |SHAP| value (in Log-Odds)") +
  xlab("") +
  coord_flip()
```